a

diff --git a/.github/workflows/preview.yaml b/.github/workflows/preview.yaml
--- a/.github/workflows/preview.yaml
+++ b/.github/workflows/preview.yaml
@@ -19,3 +19,16 @@ jobs:
         run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
       - name: Deploy Project Artifacts to Vercel
         run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
+      - name: use Node.js 16.x
+        uses: actions/setup-node@v1
+        with:
+          node-version: 16.x
+      - name: npm install and build
+        run: |
+          npm install
+          npm run build
+          npm start
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
